# base Image
FROM pytorch/pytorch:1.7.0-cuda11.0-cudnn8-devel
# ENV DEBIAN_FRONTEND=noninteractive


# add apt-source
RUN sed -i "s#archive.ubuntu.com#mirrors.aliyun.com#g" /etc/apt/sources.list && \
    sed -i "s#security.ubuntu.com#mirrors.aliyun.com#g" /etc/apt/sources.list

# get public key for aliyun server
RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com A4B469963BF863CC 

# update apt soutce list and install essential software
RUN apt-get update && apt-get install -y --no-install-recommends \
       build-essential cmake \
       libgtk-3-dev \
       libboost-all-dev \
       && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# set pip source
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
RUN pip config set global.trusted-host mirrors.aliyun.com

# pip install
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir diffusers gradio==3.20.0 opencv-python segment_anything transformers


EXPOSE 8001
EXPOSE 8002


